version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  web:
    build: ../../../../AppData/Roaming/JetBrains/PyCharmCE2024.1/scratches
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"

  celery:
    build: ../../../../AppData/Roaming/JetBrains/PyCharmCE2024.1/scratches
    command: celery -A task_manager worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - web
      - rabbitmq

  flower:
    build: ../../../../AppData/Roaming/JetBrains/PyCharmCE2024.1/scratches
    command: celery -A task_manager flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
      - web
